version: "3.3"
services:
  db:
    image: mysql:5.7.9
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: car_app
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3306
    volumes:
      - wancloudsappdbvolume:/var/lib/mysql

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 app:app --timeout 400
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+mysqldb://root:root@db/car_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/lib/app
    depends_on:
      - db
    restart: always

  redis:
    container_name: redis
    image: redis:5.0.5
    hostname: redis
    restart: always

  worker:
    container_name: celery_worker
    build:
      context: .
    hostname: worker
    command: celery -A celery_task.background_task.celery worker --loglevel=info
    restart: always
    volumes:
      - .:/car_app_file
    links:
      - redis
    depends_on:
      - app
      - redis

  celery-beat:
      container_name: celery-beat
      build:
        context: .
      command: celery -A celery_task.background_task.celery beat
      restart: always
      volumes:
        - .:/car_app_file/beat
      depends_on:
        - worker
        - app
        - redis

volumes:
  wancloudsappdbvolume:
