"""empty message

Revision ID: 80834e51ed79
Revises: 
Create Date: 2023-01-16 12:38:00.397598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80834e51ed79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('object_id', sa.String(length=45), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=45), nullable=True),
    sa.Column('model', sa.String(length=45), nullable=True),
    sa.Column('category', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.String(length=45), nullable=True),
    sa.Column('updated_at', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_table('user',
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('car')
    # ### end Alembic commands ###
